name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  pydantic-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: python -m pytest tests/test_pydantic.py -v

  ai-summarize-validation:
    runs-on: ubuntu-latest
    environment: snapplai
    env:
      LLM_GEMINI: ${{ secrets.LLM_GEMINI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: python -m pytest tests/test_ai_summarize.py -v

  ai-analyze-validation:
    runs-on: ubuntu-latest
    environment: snapplai
    env:
      LLM_GEMINI: ${{ secrets.LLM_GEMINI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: python -m pytest tests/test_ai_analyze.py -v

  smtp-validation:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.12"
        - run: pip install -r requirements.txt
        - run: pip install pytest
        - run: python -m pytest tests/test_smtp.py -v
      